### ISSUE TITLE
Power properties incorrectly defined on platforms

### ISSUE THREAD

**Issue by lccasagrande** [oar-team/batsim#45]
Hey guys, I have faced some little problems with Batsim.

First, I could not install it by following the instructions in the doc/run_batsim.md. I had some weird problems with packages that uses the **ocaml_batteries** and had to remove them in order to install it. It worked right out of the box after that , are these packages really needed? I'm not so sure.

After that, I tried to enable the SimGrid energy plugin using the platforms and workloads from this repo and I've faced another problem: 

> /tmp/nix-build-simgrid-batsim.drv-0/simgrid/src/surf/plugins/energy.cpp:210: [root/CRITICAL] Power properties incorrectly defined - could not retrieve idle, min and max power values for host master_host

I checked the platform files and the [SimGrid documentation](http://simgrid.gforge.inria.fr/simgrid/3.20/doc/group__plugin__energy.html) and find out that the property "**watt_per_state**" should have another value for the **AllCores**, but in the "**What if the host has only one core?**" section it says that it's OK to just have two values with you have only one core. I've tried to force the use of 1 core with the proper attribute, but I had an error: "Bad attribute cores in host element start tag". I've tried all the energy platforms in this repo and had the same problem. 

To fix it, I had to repeat the last value in watt_per_state of each host to be able to run it using the energy plugin. It would be nice to fix it for others facing the same problem.

You did a nice work on this simulator. It will save me a lot of time, very good work.

Best regards.

**Comment by mpoquet** [comment]
Hello Lucas,

Thanks for contributing to Batsim! :)

### Nix issue
Indeed, there was a problem in the definition of some Nix packages in [datamovepkgs](https://gitlab.inria.fr/vreis/datamove-nix). `ocaml_batteries` was used instead of `batteries`, causing the failure of any installation via `nix-env -i` (unless `-A` is used, as in this case only the required descriptions are evaluated). This should be fixed in [e32b955](https://gitlab.inria.fr/vreis/datamove-nix/commit/e32b955bc6e4aa0f762c2a7969cedaf0bc9cdf33).

### Energy platform definition issue
The problem you encountered probably comes from a version mismatch between SimGrid and the platform file. The platform files in Batsim's codebase (in `platforms/`) are usually working with their corresponding SimGrid version:
- Upstream Batsim (e.g., 1a5f224), using upstream SimGrid (tested with 5256bf572). This is the recommended version unless you need to kill jobs that are being started. Some of the platform files are tested by Batsim's CI on each commit ([there](https://framagit.org/batsim/batsim/pipelines/67966)) — notably `energy_platform_homogeneous_no_net_128.xml` and `cluster_energy128.xml`. This will be the next Batsim release as soon as all corner-case kill tests pass again.
- Batsim 2.0.0, using a [specific SimGrid fork](https://github.com/freuk/simgrid). This is the recommended version if you heavily rely on job kills. This SimGrid version is quite old (4818 commits behind upstream as I write these lines) and the platform description format has changed since then.

As it seems you are interested in studying energy-related phenomena with Batsim, please note that your results may be impacted by an [ongoing SimGrid issue](https://github.com/simgrid/simgrid/issues/189) about the energy consumption of (1-core) hosts executing parallel tasks.

Best regards,
Millian

**Comment by lccasagrande** [comment]
Yes, I'm actually developing a scheduling algorithm to minimize energy consumption and using Batsim to evaluate it.

Thanks for point me that out.

Best Regards.

**Comment by mpoquet** [comment]
Should we close this issue @lccasagrande?

**Comment by lccasagrande** [comment]
Yes for sure, thanks for the help.

**Comment by lccasagrande** [comment]
Yes for sure, thanks for the help.
